---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitops
spec:
  chart:
    spec:
      chart: gitlab
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gitlab
      version: 5.10.2
  interval: 1m0s
  values:
    certmanager:
      install: false
    gitlab:
      gitlab-shell:
        maxReplicas: 1
        minReplicas: 1
        service:
          nodePort: 32022
          type: NodePort
      sidekiq:
        maxReplicas: 1
        minReplicas: 1
      webservice:
        maxReplicas: 1
        minReplicas: 1
    gitlab-runner:
      install: false
    global:
      hosts:
        domain: 192.168.59.163.nip.io
        externalIP: 192.168.59.163
      ingress:
        class: nginx
        configureCertmanager: false
      rails:
        bootsnap:
          enabled: false
      shell:
        port: 32022
    nginx-ingress:
      enabled: false
    prometheus:
      install: false
    registry:
      hpa:
        maxReplicas: 1
        minReplicas: 1
  valuesFrom:
  - kind: Secret
    name: gitlab-gitlab-license
    valuesKey: license
    targetPath: global.gitlab.license.secret

