---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitops
spec:
  chart:
    spec:
      chart: gitlab
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gitlab
      version: 5.10.2
  interval: 1m0s
  values:
    certmanager:
      install: false
    gitlab:
      gitlab-shell:
        service:
          nodePort: 32022
          type: NodePort
    gitlab-runner:
      certsSecretName: gitlab-wildcard-tls-chain
    global:
      gitlab:
        license:
          secret: gitlab-gitlab-license
      hosts:
        domain: 192.168.99.100.nip.io
        externalIP: 192.168.99.100
      ingress:
        class: nginx
        configureCertmanager: false
      shell:
        port: 32022
    nginx-ingress:
      enabled: false
  valuesFrom:
  - kind: Secret
    name: gitlab-gitlab-license
    valuesKey: license

